export default {
  one: {
    rules: [
      "global.mineMinerals",
      "global.noGas",
      "stepOne.minimapAttack",
      "stepOne.noBabysitting",
      "global.noCommandCard",
      "global.unitsPerProduction",
      "global.productionPerBase",
    ],
    units: {
      terran: ["scv", "marine"],
      protoss: ["probe", "zealot"],
      zerg: ["drone", "zergling", "queen", "overlord"],
      extra: {
        number: 0,
        units: {
          terran: [],
          protoss: [],
          zerg: [],
        },
      },
    },
    suggestions: {
      terran: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBasesNoGas",
        "global.aggresive",
        "global.economy",
        "global.ccEnergy",
      ],
      protoss: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBasesNoGas",
        "global.aggresive",
        "global.economy",
        "global.nexusEnergy",
      ],
      zerg: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBasesNoGas",
        "global.aggresive",
        "global.economy",
        "global.queenEnergy",
      ],
    },
  },
  two: {
    rules: [
      "global.mineMinerals",
      "global.noGas",
      "global.unitControl",
      "global.noCommandCard",
      "global.unitsPerProduction",
      "global.productionPerBase",
    ],
    units: {
      terran: ["scv", "marine"],
      protoss: ["probe", "zealot"],
      zerg: ["drone", "zergling", "queen", "overlord"],
      extra: {
        number: 0,
        units: {
          terran: [],
          protoss: [],
          zerg: [],
        },
      },
    },
    suggestions: {
      terran: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBasesNoGas",
        "global.aggresive",
        "global.economy",
        "global.ccEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      protoss: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBasesNoGas",
        "global.aggresive",
        "global.economy",
        "global.nexusEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      zerg: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBasesNoGas",
        "global.aggresive",
        "global.economy",
        "global.queenEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
    },
  },
  three: {
    rules: [
      "global.mineMinerals",
      "global.mineGas",
      "global.noCommandCard",
      "global.unitsPerProduction",
      "global.productionPerBase",
    ],
    units: {
      terran: ["scv", "marine", "hellion", "hellbat", "medivac"],
      protoss: ["probe", "zealot", "observer", "prism"],
      zerg: ["drone", "zergling", "queen", "overlord", "overseer"],
      extra: {
        number: 0,
        units: {
          terran: [],
          protoss: [],
          zerg: [],
        },
      },
    },
    suggestions: {
      terran: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.ccEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      protoss: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.nexusEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      zerg: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.queenEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
    },
  },
  four: {
    rules: [
      "global.mineMinerals",
      "global.mineGas",
      "global.noCommandCard",
      "global.unitsPerProduction",
      "global.productionPerBase",
    ],
    units: {
      terran: ["scv", "marine", "hellion", "hellbat", "medivac"],
      protoss: ["probe", "zealot", "observer", "prism"],
      zerg: ["drone", "zergling", "queen", "overlord", "overseer"],
      extra: {
        number: 1,
        units: {
          terran: [
            "marauder",
            "reaper",
            "thor",
            "cyclone",
            "tank",
            "ghost",
            "viking",
            "battlecruiser",
            "liberator",
            "banshee",
            "raven",
            "mine",
          ],
          protoss: [
            "stalker",
            "adept",
            "sentry",
            "immortal",
            "colossus",
            "disruptor",
            "dt",
            "ht",
            "archon",
            "void",
            "oracle",
            "tempest",
            "carrier",
            "phoenix",
          ],
          zerg: [
            "roach",
            "baneling",
            "ravager",
            "hydralisk",
            "lurker",
            "ultralisk",
            "mutalisk",
            "swarm",
            "brood",
            "infestor",
            "viper",
            "corruptor",
          ],
        },
      },
    },
    suggestions: {
      terran: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.ccEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      protoss: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.nexusEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      zerg: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.queenEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
    },
  },
  five: {
    rules: [
      "global.mineMinerals",
      "global.mineGas",
      "global.noCommandCard",
      "global.unitsPerProduction",
      "global.productionPerBase",
    ],
    units: {
      terran: ["scv", "marine", "hellion", "hellbat", "medivac"],
      protoss: ["probe", "zealot", "observer", "prism"],
      zerg: ["drone", "zergling", "queen", "overlord", "overseer"],
      extra: {
        number: 2,
        units: {
          terran: [
            "marauder",
            "reaper",
            "thor",
            "cyclone",
            "tank",
            "ghost",
            "viking",
            "battlecruiser",
            "liberator",
            "banshee",
            "raven",
            "mine",
          ],
          protoss: [
            "stalker",
            "adept",
            "sentry",
            "immortal",
            "colossus",
            "disruptor",
            "dt",
            "ht",
            "archon",
            "void",
            "oracle",
            "tempest",
            "carrier",
            "phoenix",
          ],
          zerg: [
            "roach",
            "baneling",
            "ravager",
            "hydralisk",
            "lurker",
            "ultralisk",
            "mutalisk",
            "swarm",
            "brood",
            "infestor",
            "viper",
            "corruptor",
          ],
        },
      },
    },
    suggestions: {
      terran: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.ccEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      protoss: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.nexusEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      zerg: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.queenEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
    },
  },
  six: {
    rules: [
      "global.mineMinerals",
      "global.mineGas",
      "global.noCommandCard",
      "global.unitsPerProduction",
      "global.productionPerBase",
    ],
    units: {
      terran: ["scv", "marine", "hellion", "hellbat", "medivac"],
      protoss: ["probe", "zealot", "observer", "prism"],
      zerg: ["drone", "zergling", "queen", "overlord", "overseer"],
      extra: {
        number: 3,
        units: {
          terran: [
            "marauder",
            "reaper",
            "thor",
            "cyclone",
            "tank",
            "ghost",
            "viking",
            "battlecruiser",
            "liberator",
            "banshee",
            "raven",
            "mine",
          ],
          protoss: [
            "stalker",
            "adept",
            "sentry",
            "immortal",
            "colossus",
            "disruptor",
            "dt",
            "ht",
            "archon",
            "void",
            "oracle",
            "tempest",
            "carrier",
            "phoenix",
          ],
          zerg: [
            "roach",
            "baneling",
            "ravager",
            "hydralisk",
            "lurker",
            "ultralisk",
            "mutalisk",
            "swarm",
            "brood",
            "infestor",
            "viper",
            "corruptor",
          ],
        },
      },
    },
    suggestions: {
      terran: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.ccEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      protoss: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.nexusEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
      zerg: [
        "global.haveFun",
        "global.experiment",
        "global.focus",
        "global.screenMovement",
        "global.screenPositions",
        "global.hotkeys",
        "global.threeBases",
        "global.aggresive",
        "global.economy",
        "global.queenEnergy",
        "global.unitActive",
        "global.avoidBaseCamara",
      ],
    },
  },
  seven: {
    rules: [],
    units: {
      terran: [],
      protoss: [],
      zerg: [],
      extra: {
        number: 0,
        units: {
          terran: [],
          protoss: [],
          zerg: [],
        },
      },
    },
  },
};
